[prometheus]
prom01 ansible_host=$IP

[grafana]
grafana01 ansible_host=$IP

[loadbalancers]
lb01 ansible_host=$IP
lb02 ansible_host=$IP

[webservers]
web01 ansible_host=$IP
web02 ansible_host=$IP
web03 ansible_host=$IP
web04 ansible_host=$IP
web05 ansible_host=$IP
[all:vars]
ansible_python_interpreter=/usr/bin/python3
