[loadbalancers]
lb01 ansible_host=10.0.2.40
lb02 ansible_host=10.0.2.41

[webservers]
web01 ansible_host=10.0.2.50
web02 ansible_host=10.0.2.60
web03 ansible_host=10.0.2.70
web04 ansible_host=10.0.2.80
web05 ansible_host=10.0.2.90
#web06 ansible_host=10.0.2.91
#web07 ansible_host=10.0.2.92
