[prometheus]
prom01 ansible_host=10.0.2.20

[grafana]
grafana01 ansible_host=10.0.2.21

[loadbalancers]
lb01 ansible_host=10.0.2.22
lb02 ansible_host=10.0.2.23

[webservers]
web01 ansible_host=10.0.2.24
web02 ansible_host=10.0.2.25
web03 ansible_host=10.0.2.26
web04 ansible_host=10.0.2.27
web05 ansible_host=10.0.2.28
#web06 ansible_host=10.0.2.91
#web07 ansible_host=10.0.2.92

[all:vars]
ansible_python_interpreter=/usr/bin/python3
